#!/usr/bin/env node
/**
 * Generate WAV audio assets for app synthesized sounds.
 *
 * Produces:
 *   assets/sounds/white-noise.wav   – 60 s loop, mono 44 100 Hz 16-bit
 *   assets/sounds/brown-noise.wav   – 60 s loop
 *   assets/sounds/chime.wav         – 2 s one-shot
 *
 * Note: rain.wav and fireplace.wav are converted from real recordings
 * (see assets/sounds/sources/) and are not generated by this script.
 */

const fs = require("fs");
const path = require("path");

const SAMPLE_RATE = 44100;
const OUT_DIR = path.resolve(__dirname, "..", "assets", "sounds");
const CROSSFADE_SEC = 0.5; // 500 ms crossfade for seamless loops

// ── helpers ──────────────────────────────────────────────────────

function writeWav(filePath, samples, sampleRate = SAMPLE_RATE) {
	const numSamples = samples.length;
	const bytesPerSample = 2; // 16-bit
	const dataSize = numSamples * bytesPerSample;
	const buffer = Buffer.alloc(44 + dataSize);

	// RIFF header
	buffer.write("RIFF", 0);
	buffer.writeUInt32LE(36 + dataSize, 4);
	buffer.write("WAVE", 8);

	// fmt chunk
	buffer.write("fmt ", 12);
	buffer.writeUInt32LE(16, 16); // chunk size
	buffer.writeUInt16LE(1, 20); // PCM
	buffer.writeUInt16LE(1, 22); // mono
	buffer.writeUInt32LE(sampleRate, 24);
	buffer.writeUInt32LE(sampleRate * bytesPerSample, 28); // byte rate
	buffer.writeUInt16LE(bytesPerSample, 32); // block align
	buffer.writeUInt16LE(16, 34); // bits per sample

	// data chunk
	buffer.write("data", 36);
	buffer.writeUInt32LE(dataSize, 40);

	for (let i = 0; i < numSamples; i++) {
		const clamped = Math.max(-1, Math.min(1, samples[i]));
		const int16 = Math.round(clamped * 32767);
		buffer.writeInt16LE(int16, 44 + i * 2);
	}

	fs.writeFileSync(filePath, buffer);
	const kb = Math.round(buffer.length / 1024);
	console.log(`  ✓ ${path.basename(filePath)} (${kb} KB)`);
}

/**
 * Create a seamless loop by generating extra samples and folding the
 * tail back into the head with an overlap-add crossfade.
 *
 * 1. Generate (targetSamples + fadeSamples) of raw audio
 * 2. Blend the extra tail onto the head
 * 3. Return only targetSamples — when the player loops back to 0,
 *    the transition is seamless because the tail was baked in.
 */
function makeLoopable(rawGenerator, durationSec) {
	const fade = Math.floor(SAMPLE_RATE * CROSSFADE_SEC);
	const targetN = SAMPLE_RATE * durationSec;
	const raw = rawGenerator(targetN + fade);

	for (let i = 0; i < fade; i++) {
		const t = i / fade; // 0 → 1
		// tail sample fades out, blended onto head which fades in
		raw[i] = raw[i] * t + raw[targetN + i] * (1 - t);
	}

	return raw.slice(0, targetN);
}

// ── generators (return raw Float64Array of requested length) ─────

function rawWhiteNoise(n) {
	const samples = new Float64Array(n);
	for (let i = 0; i < n; i++) {
		samples[i] = (Math.random() * 2 - 1) * 0.08;
	}
	return samples;
}

function rawBrownNoise(n) {
	const samples = new Float64Array(n);
	let last = 0;
	for (let i = 0; i < n; i++) {
		const white = Math.random() * 2 - 1;
		last = (last + 0.02 * white) / 1.02;
		samples[i] = last * 3.5;
	}
	// Normalize
	let max = 0;
	for (let i = 0; i < n; i++) max = Math.max(max, Math.abs(samples[i]));
	if (max > 0) for (let i = 0; i < n; i++) samples[i] = (samples[i] / max) * 0.2;
	return samples;
}

function generateChime(durationSec) {
	const n = SAMPLE_RATE * durationSec;
	const samples = new Float64Array(n);
	const fundamentals = [523.25, 659.25, 783.99]; // C5, E5, G5
	for (let i = 0; i < n; i++) {
		const t = i / SAMPLE_RATE;
		const env = Math.exp(-t * 2.0) * 0.35;
		let val = 0;
		for (const freq of fundamentals) {
			val += Math.sin(2 * Math.PI * freq * t) * env;
			val += Math.sin(2 * Math.PI * freq * 2 * t) * env * 0.3;
		}
		samples[i] = val / fundamentals.length;
	}
	const fadeIn = Math.floor(SAMPLE_RATE * 0.005);
	for (let i = 0; i < fadeIn; i++) samples[i] *= i / fadeIn;
	return samples;
}

// ── main ─────────────────────────────────────────────────────────

fs.mkdirSync(OUT_DIR, { recursive: true });
console.log("Generating audio assets…\n");

writeWav(path.join(OUT_DIR, "white-noise.wav"), makeLoopable(rawWhiteNoise, 60));
writeWav(path.join(OUT_DIR, "brown-noise.wav"), makeLoopable(rawBrownNoise, 60));
writeWav(path.join(OUT_DIR, "chime.wav"), generateChime(2));

console.log("\nDone ✓");
